### ISSUE TITLE
Hacktoberfest-2020

### ISSUE THREAD

**Issue by akashksinghal** [akashksinghal/Python_Ciphers#1]
Hello folks, Want to contribute to Hacktoberfest.
Confused about what to contribute?
Let's make your task simpler.
Go and check out the README of this repo and start contributing!
Generate PRs for Hacktoberfest-2020 just by creating simple and efficient python programs to do your daily jobs
Happy Learning!!!

**Comment by MayankGeek** [comment]
Hello,
Can I contribute?

**Comment by akashksinghal** [comment]
@MayankGeek Yes, you can contribute.

**Comment by MayankGeek** [comment]
I have added a script please review it.
